---
# Creating server policies specific to Converged Infrastrucure stack. These policies are used
# to configure the Server Profile Template(s)

- name: "Conifgure IMM Server Policies"
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/secrets.yml
    - group_vars/ucs.yml
    - group_vars/all.yml

  # Create Various Server Policies
  roles:
    - role: create_server_policies
